# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Giovanni Filomeno
first_name: Giovanni
middle_name:
last_name: Filomeno
email:
description: >
  AI/ML Lead Engineer @ BMW Group | Dr.-Ing. in Numerical Optimization
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

keywords: ai, machine-learning, bmw, optimization, multimodal-learning, recsys, dcase
lang: en
icon: ⚛️

# URL configurata per il tuo username
url: https://giofilo.github.io
baseurl: # Lascia vuoto perché è un repo root user
last_updated: false

# -----------------------------------------------------------------------------
# Theme & Layout
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
max_width: 930px
navbar_fixed: true
footer_fixed: true

# -----------------------------------------------------------------------------
# Social & Analytics
# -----------------------------------------------------------------------------
# Questo abilita i badge di Google Scholar accanto ai paper
enable_publication_badges:
  google_scholar: true
  altmetric: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true
  publications:
    output: true

# Opzioni professionali
enable_darkmode: true
enable_math: true